# config.py

# ===== MARKET API =====
MARKET_API_KEY = "d143e9bb8b0c4d7487872fd699280bde"

# ===== MARKET SETTINGS =====
SYMBOL = "XAUUSD"
TIMEFRAME = "15m"
CANDLE_LIMIT = 200

# ===== RISK SETTINGS =====
RISK_REWARD = 2
COOLDOWN_SECONDS = 300

# ===== TELEGRAM =====
BOT_NAME = "XAUUSD SMC BOT"
