# config.py

# ===== MARKET SETTINGS =====
SYMBOL = "XAUUSD"
TIMEFRAME = "15m"
CANDLE_LIMIT = 200

# ===== RISK SETTINGS =====
RISK_REWARD = 2      # 1:2 RR
COOLDOWN_SECONDS = 300  # 5 minutes

# ===== TELEGRAM =====
BOT_NAME = "XAUUSD SMC BOT"
